export const Colors = {
  primary: '#ffffff',
  foreground: '#ffffff',
  alterBackground: '#28305a',
  background: '#1f2449',
  neutral: '#1f2449',
  neutral2: '#1e2245',
  hint: '#acacd2',
  gradient1: '#00d4d0',
  gradient2: '#7028e4',
  separator: '#1b1f40',
  inactive: '#343f75',
  accent: '#167ed9'
};

const FontBaseValue = 18;

export const DarkKittenTheme = {
  name: 'dark',
  colors: {
    primary: Colors.primary,
    primaryActive: Colors.primaryActive,
    success: Colors.success,
    successActive: Colors.successActive,
    info: Colors.info,
    infoActive: Colors.infoActive,
    warning: Colors.warning,
    warningActive: Colors.warningActive,
    danger: Colors.danger,
    dangerActive: Colors.dangerActive,
    foreground: Colors.foreground,
    background: Colors.background,
    overlay: Colors.overlay,
    twitter: Colors.primary,
    google: Colors.primary,
    facebook: Colors.primary,
    text: {
      base: Colors.foreground,
      alter: Colors.foreground,
      secondary: Colors.foreground,
      overlay: Colors.foreground,
      accent: Colors.foreground,
      hint: Colors.hint,
      icon: Colors.hint,
    },
    back: {
      base: Colors.background,
      alternative: Colors.background,
      inactive: Colors.inactive,
      primary: Colors.primary,
      primaryActive: Colors.neutral,
      success: Colors.success,
      successActive: Colors.successActive,
      info: Colors.info,
      infoActive: Colors.infoActive,
      warning: Colors.warning,
      warningActive: Colors.warningActive,
      danger: Colors.danger,
      dangerActive: Colors.dangerActive,
      foreground: Colors.foreground,
      background: Colors.background,
      outline: 'transparent',
      material: Colors.primary,
      neutral: Colors.neutral,
      disabled: Colors.neutral2,
      gradient1: Colors.gradient1,
      gradient2: Colors.gradient2,
      overlay: Colors.overlay,
      control: Colors.alterBackground,
      messageIn: Colors.alterBackground,
      messageOut: Colors.inactive,
      highlight: Colors.accent
    },
    border: {
      base: Colors.background,
      underline: Colors.separator,
      solid: '#0000003B',
      material: Colors.warning,
      disabled: Colors.neutral,
      card: '#00000014',
      hint: Colors.hint
    },
    gradients: {
      base: [Colors.gradient1, Colors.gradient2],
      visa: ['#63e2ff', '#712ec3'],
      mastercard: ['#febb5b', '#f24645'],
      axp: ['#42e695', '#3bb2bb'],
    }
  },
  fonts: {
    sizes: {
      h0: 32,
      h1: 26,
      h2: 24,
      h3: 20,
      h4: 18,
      h5: 16,
      h6: 15,
      p1: 16,
      p2: 15,
      p3: 15,
      p4: 13,
      s1: 15,
      s2: 14,
      s3: 14,
      s4: 12,
      s5: 12,
      s6: 13,
      s7: 10,
      base: FontBaseValue,
      small: FontBaseValue * .8,
      medium: FontBaseValue,
      large: FontBaseValue * 1.2,
      xlarge: FontBaseValue / 0.75,
      xxlarge: FontBaseValue * 1.6,

    },
    lineHeights: {
      medium: 18,
      big: 24
    },
    family: {
      light: 'Roboto-Light',
      regular: 'Roboto-Regular',
      bold: 'Roboto-Medium',
      logo: 'Righteous-Regular',
    }
  }
};